"""
Code Sandbox Service v2 — Secure execution environment for LLM-generated Python code.

This is the core runtime for Code Mode. The LLM writes Python code against a typed API
(generated by ToolAPIGenerator), and this sandbox executes it safely.

Security model (defense in depth):
1. AST-level validation — Block dangerous patterns before execution
2. Restricted builtins — Only safe builtins exposed
3. Module allowlist — Only approved standard library modules
4. Network isolation — No access to os, sys, subprocess, socket, http
5. Resource limits — 30s timeout, max 25 tool calls per execution
6. Import interception — Custom __import__ that only allows approved modules

Inspired by:
- Cloudflare Code Mode (V8 isolate-based sandbox)
- FastMCP CodeMode transform (MontySandboxProvider)
- Anthropic Programmatic Tool Calling
"""

import ast
import asyncio
import datetime
import hashlib
import json
import logging
import math
import re
import textwrap
import time
import uuid
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)

# Maximum number of tool calls allowed per single code execution
MAX_TOOL_CALLS_PER_EXECUTION = 25

# Maximum execution time in seconds
EXECUTION_TIMEOUT = 30.0

# Maximum output log size (characters)
MAX_OUTPUT_SIZE = 50_000

# Patterns that should NEVER appear in LLM-generated code
BLOCKED_AST_NODES = {
    # System access
    ast.Import,      # Use safe_import instead
    ast.ImportFrom,  # Use safe_import instead  
}

# Blocked attribute access patterns (strings that should not appear in code)
BLOCKED_PATTERNS = [
    "__import__",
    "__subclasses__",
    "__bases__",
    "__globals__",
    "__code__",
    "__builtins__",
    ".__class__",
    "breakpoint",
    "compile(",
    "globals(",
    "locals(",
    "getattr(",
    "setattr(",
    "delattr(",
    "open(",
    "exec(",
    "eval(",
    # OS/system access
    "os.system",
    "os.popen",
    "os.exec",
    "subprocess",
    "shutil",
    # Network access
    "socket",
    "urllib",
    "http.client",
    "requests.",
    "aiohttp.",
    "httpx.",
    # File system
    "pathlib",
    "tempfile",
    "os.path",
    "os.remove",
    "os.unlink",
    "os.mkdir",
    "os.rmdir",
]


class CodeSandboxService:
    """
    A service for executing LLM-generated Python code in a restricted environment.
    
    This enables "Code Mode" where the LLM orchestrates tools by writing Python code
    against a typed API rather than returning multiple tool-call JSON objects.
    
    The sandbox provides:
    - A typed API (classes with async methods) for each connected platform
    - Standard library modules: json, math, datetime, re, hashlib, uuid
    - A `_call(tool_name, params)` function for raw tool invocation
    - A `print()` function that captures output to an internal log
    - A `result` variable that captures the final output
    
    Security guarantees:
    - No file system access
    - No network access
    - No process spawning
    - No module imports outside the allowlist
    - AST-level validation before execution
    - 30-second timeout
    - Max 25 tool calls per execution
    """
    
    def __init__(self):
        self.allowed_modules = {
            "json": json,
            "math": math,
            "datetime": datetime,
            "re": re,
            "hashlib": hashlib,
            "uuid": uuid,
        }
        
        self.allowed_builtins = {
            # Core types
            "int": int,
            "float": float,
            "str": str,
            "bool": bool,
            "list": list,
            "dict": dict,
            "set": set,
            "tuple": tuple,
            "bytes": bytes,
            "bytearray": bytearray,
            "type": type,
            "None": None,
            "True": True,
            "False": False,
            # Iteration
            "range": range,
            "enumerate": enumerate,
            "zip": zip,
            "map": map,
            "filter": filter,
            "reversed": reversed,
            "sorted": sorted,
            # Aggregation
            "len": len,
            "sum": sum,
            "min": min,
            "max": max,
            "abs": abs,
            "round": round,
            "any": any,
            "all": all,
            # Type checking
            "isinstance": isinstance,
            "issubclass": issubclass,
            "hasattr": hasattr,
            "callable": callable,
            # String/repr
            "repr": repr,
            "format": format,
            "chr": chr,
            "ord": ord,
            # Exceptions (needed for try/except)
            "Exception": Exception,
            "ValueError": ValueError,
            "TypeError": TypeError,
            "KeyError": KeyError,
            "IndexError": IndexError,
            "AttributeError": AttributeError,
            "RuntimeError": RuntimeError,
            "StopIteration": StopIteration,
        }
    
    async def execute_script(
        self,
        code: str,
        call_tool: Callable,
        api_context: str = "",
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Executes a Python script in the sandboxed environment.
        
        Args:
            code: The Python code to execute (written by the LLM)
            call_tool: Async callable for invoking platform tools
            api_context: Generated typed API string to inject (from ToolAPIGenerator)
            metadata: Optional metadata (user_id, trace_id, etc.) for observability
            
        Returns:
            {
                "success": bool,
                "result": Any,           # Value of the `result` variable
                "output_log": list[str],  # Captured print() output
                "tools_invoked": list,    # Tools called during execution
                "execution_time_ms": int, # Wall clock time
                "error": str | None,      # Error message if failed
                "error_type": str | None, # Error classification
            }
        """
        start_time = time.time()
        
        # 1. Clean the code
        code = self._clean_code(code)
        
        # 2. Security validation (AST + pattern check)
        validation = self._validate_code(code)
        if not validation["safe"]:
            return {
                "success": False,
                "result": None,
                "output_log": [],
                "tools_invoked": [],
                "execution_time_ms": int((time.time() - start_time) * 1000),
                "error": f"Security violation: {validation['reason']}",
                "error_type": "SECURITY_VIOLATION",
            }
        
        # 3. Build the execution context
        tool_call_tracker = {"count": 0, "calls": []}
        
        async def tracked_call_tool(tool_name: str, params: Dict[str, Any] = None):
            """Wrapper that tracks and limits tool calls from within the sandbox."""
            if params is None:
                params = {}
            
            # Prevent recursion
            if tool_name == "execute_python_code":
                raise ValueError("Nested code execution is not permitted.")
            
            # Enforce call limit
            tool_call_tracker["count"] += 1
            if tool_call_tracker["count"] > MAX_TOOL_CALLS_PER_EXECUTION:
                raise RuntimeError(
                    f"Tool call limit exceeded ({MAX_TOOL_CALLS_PER_EXECUTION} max). "
                    "Break your task into smaller steps."
                )
            
            # Track the call
            tool_call_tracker["calls"].append({
                "tool_name": tool_name,
                "params": params,
                "call_number": tool_call_tracker["count"],
            })
            
            # Execute via the real tool executor
            result = await call_tool(tool_name, params)
            return result
        
        # 4. Wrap the code in an async function with API context
        wrapped_code = self._build_wrapped_code(code, api_context)
        
        # 5. Setup restricted globals
        def safe_import(name, globals=None, locals=None, fromlist=(), level=0):
            base_name = name.split('.')[0]
            if base_name in self.allowed_modules:
                return self.allowed_modules[base_name]
            raise ImportError(f"Import of module '{name}' is not allowed in the sandbox.")
        
        sandbox_globals = {
            "__builtins__": {
                **self.allowed_builtins,
                "__import__": safe_import,
                "print": print,  # Will be overridden inside the wrapper
            },
        }
        sandbox_globals.update(self.allowed_modules)
        
        sandbox_locals = {}
        
        try:
            # 6. Compile and execute the definition
            exec(wrapped_code, sandbox_globals, sandbox_locals)
            
            # 7. Extract and run the generated async function
            main_func = sandbox_locals.get("__sandbox_main")
            if not main_func:
                raise ValueError("Failed to compile sandbox function")
            
            # 8. Run with timeout
            script_result, output_log = await asyncio.wait_for(
                main_func(tracked_call_tool),
                timeout=EXECUTION_TIMEOUT
            )
            
            # Truncate output if too large
            if output_log:
                total_chars = sum(len(line) for line in output_log)
                if total_chars > MAX_OUTPUT_SIZE:
                    output_log = output_log[:20]
                    output_log.append(f"... (output truncated, exceeded {MAX_OUTPUT_SIZE} chars)")
            
            execution_time_ms = int((time.time() - start_time) * 1000)
            
            return {
                "success": True,
                "result": script_result,
                "output_log": output_log,
                "tools_invoked": tool_call_tracker["calls"],
                "execution_time_ms": execution_time_ms,
                "error": None,
                "error_type": None,
            }
            
        except asyncio.TimeoutError:
            logger.error("Sandbox execution timed out")
            return {
                "success": False,
                "result": None,
                "output_log": [],
                "tools_invoked": tool_call_tracker["calls"],
                "execution_time_ms": int(EXECUTION_TIMEOUT * 1000),
                "error": f"Execution timed out after {EXECUTION_TIMEOUT:.0f} seconds. "
                         "Possible infinite loop or very slow tool calls.",
                "error_type": "TIMEOUT",
            }
        except RuntimeError as e:
            if "Tool call limit" in str(e):
                return {
                    "success": False,
                    "result": None,
                    "output_log": [],
                    "tools_invoked": tool_call_tracker["calls"],
                    "execution_time_ms": int((time.time() - start_time) * 1000),
                    "error": str(e),
                    "error_type": "RESOURCE_LIMIT",
                }
            raise
        except Exception as e:
            logger.error(f"Sandbox execution error: {e}")
            return {
                "success": False,
                "result": None,
                "output_log": [],
                "tools_invoked": tool_call_tracker["calls"],
                "execution_time_ms": int((time.time() - start_time) * 1000),
                "error": f"Execution error: {str(e)}",
                "error_type": "EXECUTION_ERROR",
            }
    
    def _validate_code(self, code: str) -> Dict[str, Any]:
        """
        Validate code safety using AST analysis and pattern matching.
        
        Returns:
            {"safe": bool, "reason": str}
        """
        # Pattern-based checks (fast, catches string-level attacks)
        for pattern in BLOCKED_PATTERNS:
            if pattern in code:
                return {
                    "safe": False,
                    "reason": f"Blocked pattern detected: '{pattern}'"
                }
        
        # AST-level analysis
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return {
                "safe": False,
                "reason": f"Syntax error: {e}"
            }
        
        for node in ast.walk(tree):
            # Block direct import statements (use __import__ via safe_import instead)
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                module_name = ""
                if isinstance(node, ast.Import):
                    module_name = node.names[0].name if node.names else ""
                elif isinstance(node, ast.ImportFrom):
                    module_name = node.module or ""
                
                base_module = module_name.split(".")[0]
                if base_module not in self.allowed_modules:
                    return {
                        "safe": False,
                        "reason": f"Import of '{module_name}' is not allowed"
                    }
            
            # Block dangerous attribute access
            if isinstance(node, ast.Attribute):
                attr_name = node.attr
                if attr_name.startswith("__") and attr_name.endswith("__"):
                    if attr_name not in ("__init__", "__str__", "__repr__", "__len__",
                                         "__getitem__", "__setitem__", "__contains__",
                                         "__iter__", "__next__", "__enter__", "__exit__",
                                         "__aenter__", "__aexit__", "__aiter__", "__anext__"):
                        return {
                            "safe": False,
                            "reason": f"Access to dunder '{attr_name}' is not allowed"
                        }
        
        return {"safe": True, "reason": ""}
    
    def _build_wrapped_code(self, code: str, api_context: str) -> str:
        """
        Wrap user code in an async function with the typed API context.
        
        The wrapper provides:
        - _call() function for raw tool invocation
        - Typed API classes (from ToolAPIGenerator)
        - Overridden print() that captures to output_log
        - result variable capture
        """
        # Build API class definitions that use _call internally
        api_section = ""
        if api_context:
            # Replace the _call references in generated API to use the real function
            api_section = textwrap.indent(api_context, "    ")
        
        wrapped = f"""
async def __sandbox_main(_call_tool_raw):
    output_log = []
    
    def sandbox_print(*args, **kwargs):
        line = " ".join(str(a) for a in args)
        output_log.append(line)
    
    print = sandbox_print
    
    # The raw tool invocation function
    async def _call(tool_name, params=None):
        return await _call_tool_raw(tool_name, params or {{}})
    
    # === Generated Tool API ===
{api_section}
    # === End Generated Tool API ===
    
    result = None
    
    # === User Code ===
{textwrap.indent(code, '    ')}
    # === End User Code ===
    
    return result, output_log
"""
        return wrapped
    
    def _clean_code(self, code: str) -> str:
        """Removes markdown formatting and normalizes the code."""
        code = code.strip()
        
        # Remove markdown code fences
        if code.startswith("```python"):
            code = code[9:]
        elif code.startswith("```py"):
            code = code[5:]
        elif code.startswith("```"):
            code = code[3:]
        
        if code.endswith("```"):
            code = code[:-3]
        
        return code.strip()
