"""auto_generated_20260428_110210

Revision ID: 0e59e524ea43
Revises: d0e619c5b57a
Create Date: 2026-04-28 11:08:57.444023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e59e524ea43'
down_revision = 'd0e619c5b57a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_events_status'), 'failed_events', ['status'], unique=False)
    op.create_index('ix_failed_events_status_retry', 'failed_events', ['status', 'retry_count'], unique=False)
    op.create_index(op.f('ix_failed_events_trace_id'), 'failed_events', ['trace_id'], unique=False)
    op.create_table('observability_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('span_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observability_logs_agent_id'), 'observability_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_observability_logs_customer_id'), 'observability_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_observability_logs_error_type'), 'observability_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_observability_logs_event_type'), 'observability_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_observability_logs_span_id'), 'observability_logs', ['span_id'], unique=False)
    op.create_index(op.f('ix_observability_logs_status'), 'observability_logs', ['status'], unique=False)
    op.create_index(op.f('ix_observability_logs_timestamp'), 'observability_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_observability_logs_tool_name'), 'observability_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_observability_logs_trace_id'), 'observability_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_observability_logs_workflow_id'), 'observability_logs', ['workflow_id'], unique=False)
    op.create_table('observability_traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('root_event', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_observability_traces_created_at'), 'observability_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_observability_traces_customer_id'), 'observability_traces', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observability_traces_customer_id'), table_name='observability_traces')
    op.drop_index(op.f('ix_observability_traces_created_at'), table_name='observability_traces')
    op.drop_table('observability_traces')
    op.drop_index(op.f('ix_observability_logs_workflow_id'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_trace_id'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_tool_name'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_timestamp'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_status'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_span_id'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_event_type'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_error_type'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_customer_id'), table_name='observability_logs')
    op.drop_index(op.f('ix_observability_logs_agent_id'), table_name='observability_logs')
    op.drop_table('observability_logs')
    op.drop_index(op.f('ix_failed_events_trace_id'), table_name='failed_events')
    op.drop_index('ix_failed_events_status_retry', table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_status'), table_name='failed_events')
    op.drop_table('failed_events')
    # ### end Alembic commands ### 