"""auto_generated_20260318_000842

Revision ID: 127b2ae8cf45
Revises: 1e27fb9852b4
Create Date: 2026-03-18 00:08:52.236273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127b2ae8cf45'
down_revision = '1e27fb9852b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_agent_configs', sa.Column('daraja_environment', sa.String(), server_default='sandbox', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa_agent_configs', 'daraja_environment')
    # ### end Alembic commands ### 