"""auto_generated_20260124_131924

Revision ID: 1de69507ccba
Revises: 99264c0ffe17
Create Date: 2026-01-24 13:19:31.217821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de69507ccba'
down_revision = '99264c0ffe17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('paystack_customer_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('paystack_authorization_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'paystack_authorization_code')
    op.drop_column('users', 'paystack_customer_code')
    # ### end Alembic commands ### 