"""auto_generated_20260317_135506

Revision ID: 1e27fb9852b4
Revises: 9a5ce7917b34
Create Date: 2026-03-17 13:56:02.903495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e27fb9852b4'
down_revision = '9a5ce7917b34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_agent_configs', sa.Column('callback_url_override', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mpesa_agent_configs', 'callback_url_override')
    # ### end Alembic commands ### 