"""auto_generated_20260130_170332

Revision ID: 33e62539497d
Revises: 6edb8ff4297f
Create Date: 2026-01-30 17:03:42.666078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33e62539497d'
down_revision = '6edb8ff4297f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('premium_link_id', sa.Integer(), nullable=True),
    sa.Column('paystack_reference', sa.String(), nullable=True),
    sa.Column('fan_email', sa.String(), nullable=True),
    sa.Column('fan_phone', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creator_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paystack_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['premium_link_id'], ['premium_links.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_transactions_id'), 'creator_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_creator_transactions_paystack_reference'), 'creator_transactions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_creator_transactions_premium_link_id'), 'creator_transactions', ['premium_link_id'], unique=False)
    op.create_index(op.f('ix_creator_transactions_profile_id'), 'creator_transactions', ['profile_id'], unique=False)
    op.add_column('tiktok_profiles', sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('tiktok_profiles', sa.Column('mpesa_withdrawal_number', sa.String(), nullable=True))
    op.alter_column('tiktok_videos', 'caption',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tiktok_videos', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tiktok_videos', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_tiktok_videos_tiktok_video_id'), table_name='tiktok_videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tiktok_videos_tiktok_video_id'), 'tiktok_videos', ['tiktok_video_id'], unique=False)
    op.alter_column('tiktok_videos', 'published_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tiktok_videos', 'scheduled_for',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tiktok_videos', 'caption',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('tiktok_profiles', 'mpesa_withdrawal_number')
    op.drop_column('tiktok_profiles', 'wallet_balance')
    op.drop_index(op.f('ix_creator_transactions_profile_id'), table_name='creator_transactions')
    op.drop_index(op.f('ix_creator_transactions_premium_link_id'), table_name='creator_transactions')
    op.drop_index(op.f('ix_creator_transactions_paystack_reference'), table_name='creator_transactions')
    op.drop_index(op.f('ix_creator_transactions_id'), table_name='creator_transactions')
    op.drop_table('creator_transactions')
    # ### end Alembic commands ### 