"""auto_generated_20260306_234539

Revision ID: 37bb38aadbef
Revises: 7b3eac9fce69
Create Date: 2026-03-06 23:46:19.427860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bb38aadbef'
down_revision = '7b3eac9fce69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('email_2fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('default_2fa_method', sa.String(), nullable=True))
    op.add_column('users', sa.Column('login_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('login_otp_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_otp_expiry')
    op.drop_column('users', 'login_otp')
    op.drop_column('user_settings', 'default_2fa_method')
    op.drop_column('user_settings', 'email_2fa_enabled')
    # ### end Alembic commands ### 