"""auto_generated_20260409_110853

Revision ID: 518c2454120e
Revises: ef93800962d1
Create Date: 2026-04-09 11:09:38.672421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518c2454120e'
down_revision = 'ef93800962d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_expiry')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ### 