"""auto_generated_20260315_172245

Revision ID: 536e7ddf484a
Revises: 37bb38aadbef
Create Date: 2026-03-15 17:23:19.156355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536e7ddf484a'
down_revision = '37bb38aadbef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('callback_urls', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_apps_client_id'), 'developer_apps', ['client_id'], unique=True)
    op.create_index(op.f('ix_developer_apps_id'), 'developer_apps', ['id'], unique=False)
    op.create_table('app_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['developer_apps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_tokens_id'), 'app_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_app_tokens_refresh_token'), 'app_tokens', ['refresh_token'], unique=True)
    op.create_table('authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['developer_apps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_codes_code'), 'authorization_codes', ['code'], unique=True)
    op.create_index(op.f('ix_authorization_codes_id'), 'authorization_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorization_codes_id'), table_name='authorization_codes')
    op.drop_index(op.f('ix_authorization_codes_code'), table_name='authorization_codes')
    op.drop_table('authorization_codes')
    op.drop_index(op.f('ix_app_tokens_refresh_token'), table_name='app_tokens')
    op.drop_index(op.f('ix_app_tokens_id'), table_name='app_tokens')
    op.drop_table('app_tokens')
    op.drop_index(op.f('ix_developer_apps_id'), table_name='developer_apps')
    op.drop_index(op.f('ix_developer_apps_client_id'), table_name='developer_apps')
    op.drop_table('developer_apps')
    # ### end Alembic commands ### 