"""auto_generated_20260126_112207

Revision ID: 6edb8ff4297f
Revises: 8aeb07ca0957
Create Date: 2026-01-26 11:22:20.553425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edb8ff4297f'
down_revision = '8aeb07ca0957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_profiles', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('tiktok_profiles', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('tiktok_profiles', sa.Column('video_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiktok_profiles', 'video_count')
    op.drop_column('tiktok_profiles', 'likes_count')
    op.drop_column('tiktok_profiles', 'following_count')
    # ### end Alembic commands ### 