"""auto_generated_20260111_144851

Revision ID: 8587c6742ee4
Revises: afc619fd4319
Create Date: 2026-01-11 14:49:01.641262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8587c6742ee4'
down_revision = 'afc619fd4319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_migration_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_migration_column')
    # ### end Alembic commands ### 