"""auto_generated_20260125_224805

Revision ID: 8aeb07ca0957
Revises: cbaaca4c3c0d
Create Date: 2026-01-25 22:48:12.379722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aeb07ca0957'
down_revision = 'cbaaca4c3c0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tiktok_user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('accessToken', sa.String(), nullable=True),
    sa.Column('refreshToken', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiktok_profiles_id'), 'tiktok_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_tiktok_profiles_tiktok_user_id'), 'tiktok_profiles', ['tiktok_user_id'], unique=False)
    op.create_index(op.f('ix_tiktok_profiles_user_id'), 'tiktok_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_tiktok_profiles_username'), 'tiktok_profiles', ['username'], unique=False)
    op.create_table('premium_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_links_id'), 'premium_links', ['id'], unique=False)
    op.create_index(op.f('ix_premium_links_profile_id'), 'premium_links', ['profile_id'], unique=False)
    op.create_table('tiktok_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('tiktok_video_id', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('privacy_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiktok_videos_id'), 'tiktok_videos', ['id'], unique=False)
    op.create_index(op.f('ix_tiktok_videos_profile_id'), 'tiktok_videos', ['profile_id'], unique=False)
    op.create_index(op.f('ix_tiktok_videos_tiktok_video_id'), 'tiktok_videos', ['tiktok_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiktok_videos_tiktok_video_id'), table_name='tiktok_videos')
    op.drop_index(op.f('ix_tiktok_videos_profile_id'), table_name='tiktok_videos')
    op.drop_index(op.f('ix_tiktok_videos_id'), table_name='tiktok_videos')
    op.drop_table('tiktok_videos')
    op.drop_index(op.f('ix_premium_links_profile_id'), table_name='premium_links')
    op.drop_index(op.f('ix_premium_links_id'), table_name='premium_links')
    op.drop_table('premium_links')
    op.drop_index(op.f('ix_tiktok_profiles_username'), table_name='tiktok_profiles')
    op.drop_index(op.f('ix_tiktok_profiles_user_id'), table_name='tiktok_profiles')
    op.drop_index(op.f('ix_tiktok_profiles_tiktok_user_id'), table_name='tiktok_profiles')
    op.drop_index(op.f('ix_tiktok_profiles_id'), table_name='tiktok_profiles')
    op.drop_table('tiktok_profiles')
    # ### end Alembic commands ### 