"""auto_generated_20260121_224410

Revision ID: 99264c0ffe17
Revises: 001
Create Date: 2026-01-21 22:44:28.274692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99264c0ffe17'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('openai_api_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('anthropic_api_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('gemini_api_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('huggingface_api_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('together_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'together_api_key')
    op.drop_column('user_settings', 'huggingface_api_key')
    op.drop_column('user_settings', 'gemini_api_key')
    op.drop_column('user_settings', 'anthropic_api_key')
    op.drop_column('user_settings', 'openai_api_key')
    # ### end Alembic commands ### 