"""auto_generated_20260317_114851

Revision ID: 9a5ce7917b34
Revises: 536e7ddf484a
Create Date: 2026-03-17 11:49:07.104482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5ce7917b34'
down_revision = '536e7ddf484a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mpesa_agent_configs', sa.Column('daraja_consumer_key', sa.String(), nullable=True))
    op.add_column('mpesa_agent_configs', sa.Column('daraja_consumer_secret', sa.String(), nullable=True))
    op.add_column('mpesa_agent_configs', sa.Column('daraja_passkey', sa.String(), nullable=True))
    op.add_column('mpesa_agent_configs', sa.Column('daraja_shortcode', sa.String(), nullable=True))
    op.add_column('mpesa_agent_configs', sa.Column('webhook_secret', sa.String(), nullable=True))
    op.create_index(op.f('ix_mpesa_agent_configs_webhook_secret'), 'mpesa_agent_configs', ['webhook_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpesa_agent_configs_webhook_secret'), table_name='mpesa_agent_configs')
    op.drop_column('mpesa_agent_configs', 'webhook_secret')
    op.drop_column('mpesa_agent_configs', 'daraja_shortcode')
    op.drop_column('mpesa_agent_configs', 'daraja_passkey')
    op.drop_column('mpesa_agent_configs', 'daraja_consumer_secret')
    op.drop_column('mpesa_agent_configs', 'daraja_consumer_key')
    # ### end Alembic commands ### 