"""auto_generated_20260131_201226

Revision ID: a679c565e0c7
Revises: 33e62539497d
Create Date: 2026-01-31 20:12:45.150436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a679c565e0c7'
down_revision = '33e62539497d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('fan_email', sa.String(), nullable=True),
    sa.Column('fan_name', sa.String(), nullable=True),
    sa.Column('fan_message', sa.Text(), nullable=True),
    sa.Column('paystack_reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creator_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_transactions_id'), 'tip_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_tip_transactions_paystack_reference'), 'tip_transactions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_tip_transactions_profile_id'), 'tip_transactions', ['profile_id'], unique=False)
    op.create_table('fan_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_link_id', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['tiktok_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_link_id'], ['premium_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'email', name='uq_fan_creator_email')
    )
    op.create_index(op.f('ix_fan_contacts_id'), 'fan_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_fan_contacts_profile_id'), 'fan_contacts', ['profile_id'], unique=False)
    op.create_table('link_click_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premium_link_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['premium_link_id'], ['premium_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_link_analytics_date', 'link_click_analytics', ['premium_link_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_link_click_analytics_id'), 'link_click_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_link_click_analytics_premium_link_id'), 'link_click_analytics', ['premium_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_click_analytics_premium_link_id'), table_name='link_click_analytics')
    op.drop_index(op.f('ix_link_click_analytics_id'), table_name='link_click_analytics')
    op.drop_index('ix_link_analytics_date', table_name='link_click_analytics')
    op.drop_table('link_click_analytics')
    op.drop_index(op.f('ix_fan_contacts_profile_id'), table_name='fan_contacts')
    op.drop_index(op.f('ix_fan_contacts_id'), table_name='fan_contacts')
    op.drop_table('fan_contacts')
    op.drop_index(op.f('ix_tip_transactions_profile_id'), table_name='tip_transactions')
    op.drop_index(op.f('ix_tip_transactions_paystack_reference'), table_name='tip_transactions')
    op.drop_index(op.f('ix_tip_transactions_id'), table_name='tip_transactions')
    op.drop_table('tip_transactions')
    # ### end Alembic commands ### 