"""auto_generated_20260125_030217

Revision ID: cbaaca4c3c0d
Revises: a7526af3b784
Create Date: 2026-01-25 03:02:27.779812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaaca4c3c0d'
down_revision = 'a7526af3b784'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_user_template')
    )
    op.create_index(op.f('ix_whatsapp_templates_id'), 'whatsapp_templates', ['id'], unique=False)
    op.create_index('ix_whatsapp_templates_user_name', 'whatsapp_templates', ['user_id', 'name'], unique=False)
    op.create_table('whatsapp_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_variables', sa.JSON(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_tag', sa.String(), nullable=True),
    sa.Column('target_contact_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='whatsappbroadcaststatus'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_broadcasts_id'), 'whatsapp_broadcasts', ['id'], unique=False)
    op.create_index('ix_whatsapp_broadcasts_scheduled', 'whatsapp_broadcasts', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_whatsapp_broadcasts_user_status', 'whatsapp_broadcasts', ['user_id', 'status'], unique=False)
    op.create_table('whatsapp_broadcast_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['whatsapp_broadcasts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'contact_id', name='uq_broadcast_contact')
    )
    op.create_index('ix_broadcast_recipients_status', 'whatsapp_broadcast_recipients', ['broadcast_id', 'status'], unique=False)
    op.create_index(op.f('ix_whatsapp_broadcast_recipients_id'), 'whatsapp_broadcast_recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_broadcast_recipients_id'), table_name='whatsapp_broadcast_recipients')
    op.drop_index('ix_broadcast_recipients_status', table_name='whatsapp_broadcast_recipients')
    op.drop_table('whatsapp_broadcast_recipients')
    op.drop_index('ix_whatsapp_broadcasts_user_status', table_name='whatsapp_broadcasts')
    op.drop_index('ix_whatsapp_broadcasts_scheduled', table_name='whatsapp_broadcasts')
    op.drop_index(op.f('ix_whatsapp_broadcasts_id'), table_name='whatsapp_broadcasts')
    op.drop_table('whatsapp_broadcasts')
    op.drop_index('ix_whatsapp_templates_user_name', table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_id'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    # ### end Alembic commands ### 