"""auto_generated_20260417_102025

Revision ID: d0e619c5b57a
Revises: ebb0213acf54
Create Date: 2026-04-17 10:20:43.783214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e619c5b57a'
down_revision = 'ebb0213acf54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messaging_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messaging_conv_activity', 'messaging_conversations', ['last_activity_at'], unique=False)
    op.create_index('ix_messaging_conv_owner_platform', 'messaging_conversations', ['owner_user_id', 'platform'], unique=False)
    op.create_index('ix_messaging_conv_sender', 'messaging_conversations', ['owner_user_id', 'sender_id'], unique=False)
    op.create_index(op.f('ix_messaging_conversations_id'), 'messaging_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_messaging_conversations_is_active'), 'messaging_conversations', ['is_active'], unique=False)
    op.create_index(op.f('ix_messaging_conversations_owner_user_id'), 'messaging_conversations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_messaging_conversations_session_key'), 'messaging_conversations', ['session_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messaging_conversations_session_key'), table_name='messaging_conversations')
    op.drop_index(op.f('ix_messaging_conversations_owner_user_id'), table_name='messaging_conversations')
    op.drop_index(op.f('ix_messaging_conversations_is_active'), table_name='messaging_conversations')
    op.drop_index(op.f('ix_messaging_conversations_id'), table_name='messaging_conversations')
    op.drop_index('ix_messaging_conv_sender', table_name='messaging_conversations')
    op.drop_index('ix_messaging_conv_owner_platform', table_name='messaging_conversations')
    op.drop_index('ix_messaging_conv_activity', table_name='messaging_conversations')
    op.drop_table('messaging_conversations')
    # ### end Alembic commands ### 