"""auto_generated_20260514_143923

Revision ID: e24ae191ac35
Revises: 0e59e524ea43
Create Date: 2026-05-14 14:40:16.414269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24ae191ac35'
down_revision = '0e59e524ea43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_audit_chain_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genesis_hash', sa.String(length=64), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_audit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('governance_decision', sa.String(length=50), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('runtime_version', sa.String(length=20), nullable=False),
    sa.Column('approved_by_human', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_record_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_skill', 'runtime_audit_records', ['skill_name'], unique=False)
    op.create_index('ix_audit_status', 'runtime_audit_records', ['status'], unique=False)
    op.create_index('ix_audit_timestamp', 'runtime_audit_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_runtime_audit_records_execution_id'), 'runtime_audit_records', ['execution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_audit_records_execution_id'), table_name='runtime_audit_records')
    op.drop_index('ix_audit_timestamp', table_name='runtime_audit_records')
    op.drop_index('ix_audit_status', table_name='runtime_audit_records')
    op.drop_index('ix_audit_skill', table_name='runtime_audit_records')
    op.drop_table('runtime_audit_records')
    op.drop_table('runtime_audit_chain_meta')
    # ### end Alembic commands ### 