"""auto_generated_20260111_150108

Revision ID: e5345983b757
Revises: 8587c6742ee4
Create Date: 2026-01-11 15:01:20.174669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5345983b757'
down_revision = '8587c6742ee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test_migration_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_migration_column', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 