#!/usr/bin/env python3
"""
Service Catalog Generator — Development Harness

Scans src/services/ and generates a structured catalog.
Output: docs/SERVICE_CATALOG.md (auto-generated, do not edit manually)

Usage:
    python scripts/generate_service_catalog.py
    python scripts/generate_service_catalog.py --output console
"""

import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List

PROJECT_ROOT = Path(__file__).parent.parent
SRC_DIR = PROJECT_ROOT / "src"
SERVICES_DIR = SRC_DIR / "services"
TESTS_DIR = PROJECT_ROOT / "tests"
DOCS_DIR = PROJECT_ROOT / "docs"


def get_service_info(filepath: Path) -> Dict:
    """Extract metadata from a service file."""
    try:
        content = filepath.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return {}

    lines = content.split("\n")
    line_count = len(lines)

    # Extract docstring
    docstring = ""
    in_doc = False
    for line in lines[:30]:
        stripped = line.strip()
        if stripped.startswith('"""') or stripped.startswith("'''"):
            if in_doc:
                break
            in_doc = True
            doc_content = stripped[3:]
            if doc_content.endswith('"""') or doc_content.endswith("'''"):
                docstring = doc_content[:-3].strip()
                break
            docstring = doc_content
            continue
        if in_doc:
            if stripped.endswith('"""') or stripped.endswith("'''"):
                docstring += " " + stripped[:-3].strip()
                break
            docstring += " " + stripped

    # Count classes and public methods
    classes = re.findall(r"^class\s+(\w+)", content, re.MULTILINE)
    methods = re.findall(r"^\s+(?:async\s+)?def\s+([a-z]\w+)", content, re.MULTILINE)
    public_methods = [m for m in methods if not m.startswith("_")]

    # Check for logger
    has_logger = bool(re.search(r"logger\s*=\s*logging\.getLogger", content))

    # Check for test file
    test_name = f"test_{filepath.stem}.py"
    has_test = (TESTS_DIR / test_name).exists()

    # Extract imports (dependencies)
    deps = set()
    for m in re.finditer(r"from\s+\.\.?(\w+)", content):
        deps.add(m.group(1))
    for m in re.finditer(r"from\s+src\.services\.(\w+)", content):
        deps.add(m.group(1))

    return {
        "name": filepath.stem,
        "path": str(filepath.relative_to(PROJECT_ROOT)),
        "lines": line_count,
        "size_kb": round(filepath.stat().st_size / 1024, 1),
        "docstring": docstring.strip()[:120] if docstring else "",
        "classes": classes,
        "public_methods": len(public_methods),
        "has_logger": has_logger,
        "has_test": has_test,
        "dependencies": sorted(deps),
    }


def generate_catalog() -> str:
    """Generate the service catalog markdown."""
    services = []

    for filepath in sorted(SERVICES_DIR.glob("*.py")):
        if filepath.name == "__init__.py":
            continue
        info = get_service_info(filepath)
        if info:
            services.append(info)

    # Generate markdown
    lines = [
        "# Service Catalog",
        "",
        f"> Auto-generated by `scripts/generate_service_catalog.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "> **Do not edit manually** — regenerate with: `python scripts/generate_service_catalog.py`",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total Services | {len(services)} |",
        f"| Total Lines | {sum(s['lines'] for s in services):,} |",
        f"| With Tests | {sum(1 for s in services if s['has_test'])} / {len(services)} |",
        f"| With Logger | {sum(1 for s in services if s['has_logger'])} / {len(services)} |",
        "",
        "## Services",
        "",
        "| Service | Size | Methods | Tests | Logger | Description |",
        "|---|---|---|---|---|---|",
    ]

    for s in sorted(services, key=lambda x: -x["lines"]):
        test_icon = "Yes" if s["has_test"] else "No"
        logger_icon = "Yes" if s["has_logger"] else "No"
        desc = s["docstring"][:60] + "..." if len(s["docstring"]) > 60 else s["docstring"]
        lines.append(
            f"| `{s['name']}` | {s['size_kb']}KB ({s['lines']}L) | "
            f"{s['public_methods']} | {test_icon} | {logger_icon} | {desc} |"
        )

    lines.extend([
        "",
        "## Missing Tests",
        "",
        "Services that need test coverage:",
        "",
    ])

    missing = [s for s in services if not s["has_test"]]
    if missing:
        for s in sorted(missing, key=lambda x: -x["lines"]):
            lines.append(f"- `{s['name']}` ({s['lines']} lines) — needs `tests/test_{s['name']}.py`")
    else:
        lines.append("All services have test files!")

    return "\n".join(lines) + "\n"


def main():
    output = "--output" in sys.argv and sys.argv[sys.argv.index("--output") + 1] == "console"

    catalog = generate_catalog()

    if output:
        print(catalog)
    else:
        DOCS_DIR.mkdir(exist_ok=True)
        output_path = DOCS_DIR / "SERVICE_CATALOG.md"
        output_path.write_text(catalog, encoding="utf-8")
        print(f"Service catalog written to {output_path.relative_to(PROJECT_ROOT)}")
        print(f"  (Run with --output console to print instead)")


if __name__ == "__main__":
    main()
